version: "3.9"

services:
  api:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=postgres-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgres-db
    networks:
      - sc-api
      - default

  postgres-db:
    image: kartoza/postgis:12.0
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DBNAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - api
    ports:
      - 80:8000 ###
    volumes:
      - static-data:/vol/static

networks:
  sc-api:
     driver: bridge

volumes:
  postgres-data:
  static-data: