# Generated by Django 3.1.7 on 2022-06-08 13:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.marker_image_file_path),
        ),
    ]
